### ISSUE TITLE
We have tried to register a center with VBCR.lic file. but we got a error.

### ISSUE THREAD

**Issue by ayanbasak** [jmGithub2021/iMediXcare#2]
In center management section after click "Add new Center", we uploads VBCR.lic file(which is provided in root directory of source code), after that a new row comes in "center management" table with value Expires On=02-23-2031(3073), Code=VBCR019, Name=iMediXcare Hospital. After Clicking its edit button a error comes, that is "ERROR YOU ARE NOT AUTHORIZED TO ACCESS FORWARD", we needs to register few centers in our system, Please help us to solve this issue.
![Capture33](https://user-images.githubusercontent.com/60224324/192092425-1af98c17-4788-40d1-a74d-0885259b23b9.PNG)

**Comment by surajitiitkgp** [comment]
Kindly update the **_UserAccessControl.json_** file located at **_iMediXCare/iMediXcare/WEB-INF/classes/_**.
